### ISSUE TITLE
Incorrect function of getting timestamp based on language choice

### ISSUE THREAD

**Issue by superlws1** [aymansalama/wikidownloader_java#14]
Expected input : URL of project+language
Actual input: void

**Comment by kesaven8** [comment]
It is taking as input : 
consider the following input below

`choice_url = base_URL + "/" + language + project_title + "/" ;`
               ` System.out.println("choice url: "+choice_url);`
               
                TimeStamp ts = new TimeStamp(choice_url);`

**Comment by superlws1** [comment]
alright, ill make changes to my code
