### ISSUE TITLE
Certain languages from project are not found

### ISSUE THREAD

**Issue by superlws1** [aymansalama/wikidownloader_java#17]
%----------wikipedia----------%
Correct: 280 / 302
No of incorrect: 2
Incorrect: {anp=Angika, be-x-old=Belarusian (Taraškievica)}

%----------wikibooks----------%
Correct: 77 / 121
No of incorrect: 1
Incorrect: {anp=Angika}

%----------wikinews----------%
Correct: 29 / 34
No of incorrect: 0
Incorrect: {}

%----------wikiquote----------%
Correct: 66 / 90
No of incorrect: 0
Incorrect: {}

%----------wikisource----------%
Correct: 63 / 69
No of incorrect: 0
Incorrect: {}

%----------wikiversity----------%
Correct: 15 / 18
No of incorrect: 0
Incorrect: {}

%----------wikivoyage----------%
Correct: 17 / 21
No of incorrect: 0
Incorrect: {}

%----------wiktionary----------%
Correct: 146 / 174
No of incorrect: 1
Incorrect: {anp=Angika}

@amirulumar hi, i have tested on all of the wikis u provided, these are the outputs. The tables are gotten from here:
[Wikibooks](https://meta.wikimedia.org/wiki/Wikibooks) 
[Wikinews](https://meta.wikimedia.org/wiki/Wikinews)
[Wikipedia](https://meta.wikimedia.org/wiki/List_of_Wikipedias/sortable)
[Wikiquote](https://meta.wikimedia.org/wiki/Wikiquote)
[Wikisource](https://meta.wikimedia.org/wiki/Wikisource)
[Wikiversity](https://meta.wikimedia.org/wiki/Wikiversity)
[Wikivoyage](https://meta.wikimedia.org/wiki/Wikivoyage)
[Wiktionary](https://meta.wikimedia.org/wiki/Wiktionary)

**Comment by amirulumar** [comment]
Hi, the Languages function was modified to use the site URLs that you provided. Please feel free to test it again to see if it works.
