### ISSUE TITLE
Latest dump is not generated during the parsing into list of timestamps

### ISSUE THREAD

**Issue by superlws1** [aymansalama/wikidownloader_java#20]
%----------enwiki----------%
Correct: 7 / 8
No of incorrect: 0
Incorrect: []
Missing: [latest/]
%----------cebwiki----------%
Correct: 10 / 11
No of incorrect: 0
Incorrect: []
Missing: [latest/]
%----------svwiki----------%
Correct: 10 / 11
No of incorrect: 0
Incorrect: []
Missing: [latest/]
%----------enwiktionary----------%
Correct: 10 / 11
No of incorrect: 0
Incorrect: []
Missing: [latest/]
%----------mgwiktionary----------%
Correct: 10 / 11
No of incorrect: 0
Incorrect: []
Missing: [latest/]
%----------alswiktionary----------%
Correct: 10 / 11
No of incorrect: 0
Incorrect: []
Missing: [latest/]

@kesaven8 hi, i noticed that all of the test cases i performed were missing the latest dump selection

**Comment by kesaven8** [comment]
hello thank you for pointing this issue . i have created a new branch and a new class as well in an attempt to solve this issue. please run the test on the branch [https://github.com/aymansalama/wikidownloader_java/tree/Timestamp-issue](url) 
and update me for the results

**Comment by superlws1** [comment]
hi, i've tested the branch and it works fine with the input i've given. Just merge the branch carefully, it's quite messy
